-- CampusTrade Database Schema (Copy And Paste Supabase SQL editor)

-- 1. Profiles Table (Linked to Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  student_id text,
  batch text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Items Table
create table public.items (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  description text,
  category text,
  price numeric,
  image_url text,
  status text default 'available',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) not null,
  receiver_id uuid references public.profiles(id) not null,
  item_id bigint references public.items(id) not null,
  message text,
  image_url text,
  read boolean default false,
  deleted_by_sender boolean default false,
  deleted_by_receiver boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.items enable row level security;
alter table public.messages enable row level security;

-- 5. RLS Policies (Security Rules)

-- Profiles
create policy "Public profiles are viewable by everyone" 
  on public.profiles for select using (true);

create policy "Users can insert their own profile" 
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update own profile" 
  on public.profiles for update using (auth.uid() = id);

-- Items
create policy "Items are viewable by everyone" 
  on public.items for select using (true);

create policy "Users can insert their own items" 
  on public.items for insert with check (auth.uid() = user_id);

create policy "Users can update their own items" 
  on public.items for update using (auth.uid() = user_id);

create policy "Users can delete their own items" 
  on public.items for delete using (auth.uid() = user_id);

-- Messages
create policy "Users can see their own messages" 
  on public.messages for select 
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Users can insert messages" 
  on public.messages for insert 
  with check (auth.uid() = sender_id);

create policy "Users can update their own messages" 
  on public.messages for update 
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- 6. Functions & Triggers

-- Auto-create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 7. Storage Buckets (Run in SQL Editor if needed)
-- insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true);
-- insert into storage.buckets (id, name, public) values ('item-images', 'item-images', true);
-- insert into storage.buckets (id, name, public) values ('chat-images', 'chat-images', true);
